### ISSUE TITLE
Change typing to allow python 3.8

### ISSUE THREAD

**Issue by raphajaner** [theRealProHacker/PyGameRecorder#1]
Hi @theRealProHacker,

Thanks for the nice work!

It seems to me that python3.10 is only required due to the used typing (e.g., using `|` for typing works only since python3.10 while you had to use `types.Union` previously). I made the changes for myself already (running python3.8) and I think it would be nice if more people could get access to your project since python3.10 is still not that commonly used.

What's your opinion on that? If you agree I can open a PR and merge my updates.

**Comment by theRealProHacker** [comment]
Thank you for raising this issue. 

I think it's a wonderful idea. You can definitely make a PR.

If you are already here, does everything else work fine? What part of the library are you using?

**Comment by raphajaner** [comment]
PR has been opened! Please let me know what you think :)

So far yes, but have used it only in limited ways yet! I'm using the library to record/save short videos during the training of an RL agent and an environment that uses pygame for visualization.
