### ISSUE TITLE
an issue in tutorial

### ISSUE THREAD

**Issue by light100bc** [theRealProHacker/PyGameRecorder#8]
following the tutorial in https://pypi.org/project/pygame-screen-record/0.0.4/
I did : `from pygame_screen_record.ScreenRecorder import ScreenRecorder,save_recording`
But it cannot import name 'save_recording' from 'pygame_screen_record.ScreenRecorder'

I looked up the code and find maybe it sould be "save_recordings" instead of "save_recording" as there is only a function called "save_recordings". I tryed to import "save_recordings". But still not work.

Can someone help, I am new to python..

**Comment by theRealProHacker** [comment]
Hi @light100bc

Thanks a lot for the spot. You did a very good job at even finding the correct version. You are absolutely correct.

Please forgive my mistake. I must have forgotten to change the tutorial after changing the code.

I'll try to get this fixed asap.

**Comment by cmahnke** [comment]
There is another issue with that `import` statement, changing it to:
```
from pygame_screen_record.ScreenRecorder import ScreenRecorder
save_recordings = ScreenRecorder.save_recordings
```
works for me, I'm on Python 3.11.7.

**Comment by theRealProHacker** [comment]
Hi @cmahnke, thanks for your comment. That's very helpful.

I feel a bit stupid about that. I think the problem is that I changed the API a few times and forgot to update the documentation in all corresponding places. 

I will fix the issue asap and release a new version. Thanks again for your message.

**Comment by theRealProHacker** [comment]
@cmahnke, I addressed the issue and also updated some other stuff. You can now simply call `recorder.save_recording(filename)` to save the last recording, which I believe is the most common use case, or `recorder.save_recordings(key, dir)` to save all recordings. 

Please let me know if you have any further issues.
